### ISSUE TITLE
interceptResponse, missing response headers

### ISSUE THREAD

**Issue by yan-064** [CodingAleCR/http_interceptor#100]
Hi,

I have some trouble, I'd like to retrieve custom header into the interceptresponse but the ResponseData object reveal only one header. Look at the screenshot. I'm searching for the Token-AuthorizationUser-Expired header and it's missing. The data contains only one header instead of 9 in the chrome network tab.

Thanks for your help.

 - Flutter version: 2.5.3
 - IDE : VS Code
 - `http_interceptor` Version 1.0.2

![image](https://user-images.githubusercontent.com/57493454/143420303-f862e76c-84f0-4a99-88d6-42e58dbae466.png)

**Comment by yan-064** [comment]
My bad ^^.

The api has to expose the header with the Access-Control-Expose-Headers header.

https://github.com/dart-lang/http/issues/409

I close.

**Comment by CodingAleCR** [comment]
I'm glad you were able to solve it! Cheers and thanks for using the library 🎉

Also, we have a beta version for 2.0.0 which refactors our internal API for a much more extensible one, feel free to try it out ;)
