### ISSUE TITLE
Migration guide link links to 404

### ISSUE THREAD

**Issue by Seferi** [CodingAleCR/http_interceptor#102]
Hi, I'm trying to migrate our app to 1.0.0. Clicking to Migration guide link inks to page not found error 404. [](https://pub.dev/documentation/http_interceptor/latest/)

I appreciate if you can direct me to your migration guide. Thanks in advance.

**Comment by CodingAleCR** [comment]
Just checked and it worked fine for me, will look into it. In the meantime, here's [the migration guide for 1.0.0](https://github.com/CodingAleCR/http_interceptor/blob/main/guides/migration_guide_1.0.0.md)
