### ISSUE TITLE
Adding the possibility to add a generic request timeout handler

### ISSUE THREAD

**Issue by javiermrz** [CodingAleCR/http_interceptor#107]
First of all, thanks for this great library, really great work!

**Is your feature request related to a problem? Please describe.**
I find it weird that there is a request timeout option, which will throw an error, but there is not an option to handle that error (to be able to, for example, show a toast with a generic error text if the timeout throws).

**Describe the solution you'd like**
The solution is actually really easy and it only requires a couple lines. In `intercepted_client.dart`, in line 242 you have this:
```dart
await send(interceptedRequest).timeout(requestTimeout!);
```

Dart lets you override a Future timeout behaviour by adding a parameter:
```dart
await send(interceptedRequest).timeout(requestTimeout!, onTimeout: _onTimeout);
```
and then you would only have to accept this new parameter in the `build` method:
```dart
InterceptedClient.build(
  ...
  requestTimeout: Duration(seconds:20),
  onRequestTimeout: Function()
)
```

**Comment by CodingAleCR** [comment]
Hey, thank you for your proposal, it makes sense to add it and simple enough.🥳

I will try to get it soon, but contributions are always welcomed 🙌🏼

**Comment by javiermrz** [comment]
I'll do a PR no problem!

**Comment by javiermrz** [comment]
Here you go 🥳 https://github.com/CodingAleCR/http_interceptor/pull/108

**Comment by CodingAleCR** [comment]
The PR has been accepted and this should be up on 2.0.0-beta.5
