### ISSUE TITLE
headers are not getting updated upon retry

### ISSUE THREAD

**Issue by santosh81066** [CodingAleCR/http_interceptor#117]
when I am trying to retry a request headers are not getting updated following is my interceptor

```dart
class AuthorizationInterceptor extends InterceptorContract {
  @override
  Future<BaseRequest> interceptRequest({required BaseRequest request}) async {
    final prefs = await SharedPreferences.getInstance();

    final extractData =
        json.decode(prefs.getString('userData')!) as Map<String, dynamic>;
    request.headers.clear();
    request.headers['Authorization'] = await extractData['accessToken'];
    print(
        'this is from AuthorizationInterceptor: ${extractData['accessToken']}');
    // TODO: implement interceptRequest

    return request;
  }



}
```

**Comment by CodingAleCR** [comment]
If you are using prereleases of `v2.0.0+beta.1` or above, then the API has changed a bit. Check out the guides for 2.0.0  if you want to know how much has changed.

In any case, here's an example of how to set headers with the new API:

```dart
class WeatherApiInterceptor extends InterceptorContract { @override Future<BaseRequest> interceptRequest({required BaseRequest request}) async { final cache = await SharedPreferences.getInstance(); final Map<String, String>? headers = Map.from(request.headers); headers?[HttpHeaders.contentTypeHeader] = "application/json"; return request.copyWith( url: request.url.addParameters({ 'appid': cache.getString(kOWApiToken) ?? '', 'units': 'metric', }), headers: headers, ); } @override Future<BaseResponse> interceptResponse( {required BaseResponse response}) async => response; }
```

**Comment by CodingAleCR** [comment]
Also, thank you for opening an issue, I appreciate you reaching out! 😄

**Comment by santosh81066** [comment]
hello sir thx for quick reply as you sujested I had changed my interceptor but the result is same
<img width="1440" alt="Screenshot 2022-08-28 at 12 36 57" src="https://user-images.githubusercontent.com/34810098/187062041-033513fb-f245-4133-834b-41c06d45d273.png">
you can see in the image that the access token which I am printing and accesstoken which I am refreshing using refresh token is same but headers not updating
```
class AuthorizationInterceptor extends InterceptorContract {
  @override
  Future<BaseRequest> interceptRequest({required BaseRequest request}) async {
    final prefs = await SharedPreferences.getInstance();

    final extractData =
        json.decode(prefs.getString('userData')!) as Map<String, dynamic>;

    final Map<String, String> headers = Map.from(request.headers);
    headers['Authorization'] = await extractData['accessToken'];
    print(
        'this is from AuthorizationInterceptor: ${extractData['accessToken']}');
    // TODO: implement interceptRequest

    return request.copyWith(
      headers: headers,
    );
  }
```

**Comment by CodingAleCR** [comment]
Taking a closer look to your retry policy (the one sent via email) I've noticed one thing: you are not returning `true` when you are refreshing your token.

```dart
class ExpiredTokenRetryPolicy extends RetryPolicy {
  BuildContext context;
  ExpiredTokenRetryPolicy(this.context);
  @override

  int get maxRetryAttempts => 2;

  @override
  Future<bool> shouldAttemptRetryOnResponse(BaseResponse response) async {
    if (response.statusCode == 401) {
      print('retry token started');
  

      await Provider.of<Auth>(context, listen: false).restoreAccessToken();
    }
    return false;
  }
}
```

This is needed because otherwise the `RetryPolicy` will not take effect and thus the requests will still use the 'old' token. Here's the example `ExpiredTokenRetryPolicy` from the `WeatherApp` provided with the library:

```dart
class ExpiredTokenRetryPolicy extends RetryPolicy {
  @override
  int get maxRetryAttempts => 2;

  @override
  Future<bool> shouldAttemptRetryOnException(
    Exception reason,
    BaseRequest request,
  ) async {
    log(reason.toString());

    return false;
  }

  @override
  Future<bool> shouldAttemptRetryOnResponse(BaseResponse response) async {
    if (response.statusCode == 401) {
      log('Retrying request...');
      final cache = await SharedPreferences.getInstance();

      cache.setString(kOWApiToken, kOpenWeatherApiKey);

      // Notice how in here the policy returns true so that the library can now
      // when to perform a retry. In this case it is when the response's status
      // code is 401 Unauthorized.
      return true;
    }

    return false;
  }
}
```

**Comment by santosh81066** [comment]
hello sir as you said I had kept return true  but I am facing exception if I get 401 response
<img width="1440" alt="Screenshot 2022-08-29 at 12 27 34" src="https://user-images.githubusercontent.com/34810098/187143261-2510ff20-a057-4069-aa7f-a8cbedd4dd7d.png">

**Comment by CodingAleCR** [comment]
This seems like a bug in the beta version. I think it was mentioned in an issue before. Will take a look and get back to you 👀

**Comment by CodingAleCR** [comment]
By any chance are you using a `MultipartRequest` to upload a file (e.g. upload profile picture to a server)?

**Comment by santosh81066** [comment]
yeah

**Comment by santosh81066** [comment]
> By any chance are you using a `MultipartRequest` to upload a file (e.g. upload profile picture to a server)?

thank you waiting for update

**Comment by santosh81066** [comment]
> This seems like a bug in the beta version. I think it was mentioned in an issue before. Will take a look and get back to you 👀

thank you waiting for update

**Comment by santosh81066** [comment]
hello sir may I know approximate next release date

**Comment by CodingAleCR** [comment]
Hey, yes, hum in terms of ETA I can't give you one, but I can confirm at the moment that it is a bug. I'm working to fix this but it might need a big refactor.

**Comment by santosh81066** [comment]
ok thank you
