### ISSUE TITLE
Why is no new version on pub.dev?

### ISSUE THREAD

**Issue by Rodsevich** [CodingAleCR/http_interceptor#141]
Tha main/mast6er branch has teh chanegs I need, why is there no pub publish anymore?

**Comment by CodingAleCR** [comment]
There have been constant pre-releases like this one: https://github.com/CodingAleCR/http_interceptor/discussions/140

Unfortunately it's still in an experimental state due to lack of resources (I do this on my own time). Still, I use the pre-releases on my apps and nothing has broke down so far.

**Comment by Rodsevich** [comment]
Thanks @CodingAleCR. Will use that and I hope you release the new version soon!
