### ISSUE TITLE
Release version

### ISSUE THREAD

**Issue by Altevir** [CodingAleCR/http_interceptor#142]
Are there any plans for a new release version compatible with the http package >= 1.0.0?

**Comment by CodingAleCR** [comment]
Yes, the idea is to have a stable 2.x release at some point.

**Comment by mark-sdb** [comment]
For what its worth, we are using 2.0.0 beta.7 in production for a couple of months now (70k DAU app) and no problems so far :-)

**Comment by CodingAleCR** [comment]
I'll see if I can publish `2.0.0` as stable in the next month or so. Thank you all for the interest

**Comment by Altevir** [comment]
@CodingAleCR 
The community is grateful, it is an essential package, easy to implement and very helpful in operations in conjunction with http.

**Comment by Altevir** [comment]
The community is grateful, it is an essential package, easy to implement and very helpful in operations in conjunction with http.

**Comment by Leptopoda** [comment]
Hi there and thanks for the package.
No pressure but do you already know when 2.0 might be ready? Is there anything the community can help with?
We'd really like to use this package but it sadly is against some regulation affecting us.

**Comment by CodingAleCR** [comment]
Version 2.0.0 is live, feel free to report any additional issues that you find on it. 3.0.0 might be in the works once [macros is stable](https://dart.dev/language/macros). It will enable much more things and it would simplify development.
