### ISSUE TITLE
Modified params are not reflecting in api call.

### ISSUE THREAD

**Issue by periyasamyshanmugam** [CodingAleCR/http_interceptor#19]
Hello,
I am modifying my request url params in my interceptor but the modified params are not reflecting in my api call.

**data.params["xyz"] = "mytoken";** 
this is how I am modifying the request params.
Please, help me with this.
Thanks.

**Comment by CodingAleCR** [comment]
Hi, I am currently checking this out since it was reported by a couple of people as well. This is definitely a bug and will fix ASAP. Thanks for writing :)

**Comment by CodingAleCR** [comment]
Hi, @periyasamyshanmugam I've being trying to reproduce your problem but can't seem to get it. Could you post the piece of code where you are using either the `HttpClientWithInterceptor` or the `HttpWithInterceptor` to see if there is something wrong with the way you are using it?

**Comment by periyasamyshanmugam** [comment]
Hi, @CodingAleCR First of all sorry for late reply.

Simply I want to modify my url params using below code.

Future<RequestData> interceptRequest({RequestData data}) async {
    try {
      data.params["tokenString"] = "XXXXXXXXXXX";
    } catch (err) {
      print(err);
    }
    return data;
  }

This is my code where I am trying to add token string to my request params. But it is not reflecting in api request url.

Thanks.

**Comment by CodingAleCR** [comment]
No worries, here to help.

I understand that part, but I can't find any issues with the library. Are you using any of the options shown as followed for doing your request: 

**Using interceptors with Client**
```dart
Client client = HttpClientWithInterceptor.build(interceptors: [
    YourInterceptor(),
]);
```

**Using interceptors without Client**
```dart
var response = await HttpWithInterceptor
      .build(interceptors: [YourInterceptor()])
      .get("<change-with-your-url>");
```

**Comment by periyasamyshanmugam** [comment]
Yes I am using without client.

```
HttpWithInterceptor.build(
        interceptors: [TokenInterceptor(context)]).post(url, body: filter)
```

Like this i anything wrong in this?

**Comment by CodingAleCR** [comment]
There doesn't seem to be anything wrong with. the code, I will keep making tests to see if I am able to reproduce it.

**Comment by CodingAleCR** [comment]
Just as a follow up question, can I see what is implemented in `TokenInterceptor`? If you want to take this to a more private discussion we can exchange emails.

**Comment by periyasamyshanmugam** [comment]
@CodingAleCR Yes I have defined and assigned my context properly.

**Comment by CodingAleCR** [comment]
Do you think maybe we could hop on a call and troubleshoot this problem? I am unable to reproduce it and I really want to help out the user's of the library. Cheers!

**Comment by 12Hemang** [comment]
Hi There, 
i am facing same issue, on 401 API get called for token refresh , and new token get saved in shared preference (same printed in log also), but after that the old request get called without token.
Is there is any way that i can modify request with new header before call in shouldAttemptRetryOnResponse method..??

**Comment by CodingAleCR** [comment]
Hi, what version of the library are you currently using? There was a bug that did not refresh interception after the first call and I'd like to verify if that is the issue you are having or if it's a different one. Thanks for writing!

**Comment by 12Hemang** [comment]
Hi thank you for quick response , its really appreciable  
Currently i m using http_interceptor: ^0.3.1 , and yes once after updating token on 401 the next call is not updated with latest data

**Comment by 12Hemang** [comment]
Hi,Thanks i updated version  http_interceptor: ^0.3.2 and issue resolved

**Comment by CodingAleCR** [comment]
I'm glad to hear that it was the issue I fixed recently 🎉 thanks for using the library and hopefully it helps you out a lot.
