### ISSUE TITLE
Question: Retry policy

### ISSUE THREAD

**Issue by smedic** [CodingAleCR/http_interceptor#28]
Thanks for this great addition to http lib.

I have a question: do we have to call synchronous function to get new token after 401 in RetryPolicy?
I saw dio enables us to call refresh in async so it's convenient for Futures.

Thanks!

**Comment by CodingAleCR** [comment]
Hi yes at the moment but not in the future, there's already code in develop branch that will allow async call to the method and will help out. Release will be out this weekend and you will be able to try it out soon 🙌🏼

**Comment by smedic** [comment]
Awesome! Thanks!
