### ISSUE TITLE
HttpClientWithInterceptor.send() issue

### ISSUE THREAD

**Issue by Bry1337** [CodingAleCR/http_interceptor#29]
HttpClientWithInterceptor does not print  request/response data when using send. 

Is this a bug?

**Comment by CodingAleCR** [comment]
Hi, at the moment we don't fully support `send` method. I am currently working on this along with multipart requests and much more. More news on this coming soon!

**Comment by CodingAleCR** [comment]
Using `send` method was added on #98 and to the 2.0.0 beta, feel free to try it out if you want ;)
