### ISSUE TITLE
Issue with Retrying requests with protobuf as response

### ISSUE THREAD

**Issue by sunnyagarwal008** [CodingAleCR/http_interceptor#39]
The `_attemptRequest` method checks if the retry policy is configured, and if yes it creates a response clone using               `ResponseData.fromHttpResponse(response)` which tries to read response body as string (response.body). This will not work if the response body is a protobuf byte array.

```
Future<Response> _attemptRequest(Request request) async {
    var response;
    try {
      // Intercept request
      request = await _interceptRequest(request);

      var stream = requestTimeout == null
          ? await send(request)
          : await send(request).timeout(requestTimeout);

      response = await Response.fromStream(stream);
      if (retryPolicy != null &&
          retryPolicy.maxRetryAttempts > _retryCount &&
          await retryPolicy.shouldAttemptRetryOnResponse(
              ResponseData.fromHttpResponse(response))) {
        _retryCount += 1;
        return _attemptRequest(request);
      }
    } catch (error) {
      if (retryPolicy != null &&
          retryPolicy.maxRetryAttempts > _retryCount &&
          retryPolicy.shouldAttemptRetryOnException(error)) {
        _retryCount += 1;
        return _attemptRequest(request);
      } else {
        rethrow;
      }
    }

    _retryCount = 0;
    return response;
  }
```

**Comment by CodingAleCR** [comment]
Hi, yes, the initial idea was to create a plugin mostly for RESTful APIs, I did not notice that people were using it for protobufs. I'm sorry you are running into this much trouble. I will definitely will add protobuf support going forward, but for now the plugin is not compatible 😕

**Comment by CodingAleCR** [comment]
Hi, I have added this to the backlog, hopefully I will have it ready soon enough, I will close the issue for now and will ping back once it's merged. Cheers!
