### ISSUE TITLE
Retry policy may got NoSuchMethodError issue

### ISSUE THREAD

**Issue by choi-seung-min** [CodingAleCR/http_interceptor#43]
I was trying to get 401 from server(i got no token when i requested). But the application did not went i expected. It passed all exception handlers i used so i checked the log and it says "type NoSuchMethodError is not type of Exception". After debugging, i noticed that retry policy is causing this issue. So now i temporarily removed retry policy with that api request. I was using firebase authentication social for login. So i request firebase auth in retry.

**Comment by choi-seung-min** [comment]
Sorry, it was firebase problem. I checked all works fine with interceptor.

**Comment by CodingAleCR** [comment]
I'm glad to hear everything is working fine now. Let me know if there is anything I can help you with. Cheers!
