### ISSUE TITLE
background json compute

### ISSUE THREAD

**Issue by ac130kz** [CodingAleCR/http_interceptor#47]
`ResponseData` object is built with a `String` based body, however I'd like to use background json decoding, which returns a Json object (examples: [official](https://flutter.dev/docs/cookbook/networking/background-parsing), [dio_flutter_transformer](https://github.com/flutterchina/dio_flutter_transformer/blob/master/lib/dio_flutter_transformer.dart)). How do I implement my interceptor?

**Comment by CodingAleCR** [comment]
Hi, this is a really nice question, as of right now, this would fit into the feature request category since the response interceptor is static typed to a String class. I will add this to the near future as I believe it is the desired behavior of intercepting a response.
