### ISSUE TITLE
Make it work with Client.send()

### ISSUE THREAD

**Issue by gregor-vi** [CodingAleCR/http_interceptor#48]
Currently it doesn't seem to work whenever using the http client's 'send()' method, which makes the interceptor useless in those cases.

**Comment by CodingAleCR** [comment]
Hi yes,  the `send` method is not currently supported, it is included more as an escape hatch. I will be adding it as soon as I get the time to do it since it's top priority.

**Comment by shyndman** [comment]
Hi @CodingAleCR,

I found myself in need of something like this, and I put together a little project demonstrating a possible approach to getting send intercepting reasonably. Nothing is too polished, but I wanted to hear your opinion.

https://github.com/shyndman/http-recorder

**Comment by CodingAleCR** [comment]
Hey @shyndman!

Thanks a lot, I will take a look at it and come back to you. I've been playing around with making send work via cloning the request but have seemed to hit a wall when copying StreamedRequests, I would love it if I can get it working before 1.0.0 gets released, your repository will definitely help me out a ton as I am sure I will learn a lot.

**Comment by shyndman** [comment]
I haven't actually tried with StreamedRequest...but its documentation is slightly worrying. I'm going to try it out and get back.

**Comment by CodingAleCR** [comment]
I will push my code to a branch so you can see where I'm going with this, any feedback is welcomed. Still haven't gotten around to checking your repository, but will probably take a look during the weekend. Cheers!

**Comment by shyndman** [comment]
So turns out my solution works fine for StreamedRequests. Woot! There are some bugs in the recorder, but I'll get them sorted.

**Comment by shyndman** [comment]
Also works for multipart requests, and completely avoids all that annoying finalization stuff they have in there. 

Works on the basis of a `ByteStream` subclass that wraps an inner stream, caches its contents, and can hand out a single-subscriber stream to anyone who calls `listen()`. Those streams have the entire sequence of bytes replayed, so nothing gets lost.

There are memory implications if you keep them around, but it's perfect what I need. And because it only uses single-subscriber streams, there's no reason that they'll be staying in memory unexpectedly.

BUT, I would much rather be using your library, and that's why I'm here. :)

**Comment by shyndman** [comment]
Pushed up the latest, which includes a demonstration of StreamedRequest interception [in the example](https://github.com/shyndman/http-recorder/blob/main/example/main.dart).

**Comment by II11II** [comment]
Any news?

**Comment by CodingAleCR** [comment]
Unfortunately it is not complete yet, as it involves quite a bit of refactoring I'm going piece by piece to make sure it does not break anything.

**Comment by shyndman** [comment]
Worth mentioning that I solidified this pattern (for a specific use case) here:
https://github.com/madewithfelt/betamax

It works great, and I'm pretty sure I fixed a couple tricky bugs during the transition from experiment to package.

**Comment by shyndman** [comment]
Oh, and worth mentioning, I'd _love_ to swap out the lower level code for your stuff if it was available.

Happy to help to, if you want it.

**Comment by CodingAleCR** [comment]
Help is always welcomed @shyndman so we could definitely collab on it 💪🏼

**Comment by CodingAleCR** [comment]
@all-contributors add @gregor-vi, @shyndman, @II11II for ideas

**Comment by CodingAleCR** [comment]
@all-contributors add @shyndman for ideas

**Comment by CodingAleCR** [comment]
@all-contributors add @II11II for ideas

**Comment by kiaxseventh** [comment]
@CodingAleCR  any news?
client.send() method are not shipped via http_interceptor Therefore, RetryPolicy and InterceptorContract do not work
i have problem for upload file with authentication

**Comment by CodingAleCR** [comment]
Still working on it, I'm having issues when trying out the implementation with different request types like Multipart or Streamed. I'm sorry for not having better news 😔

**Comment by shyndman** [comment]
Trying out the Betamax implementation? What are you running into?

**Comment by vandres** [comment]
I also would love to see a solution for that. Using a library, which is dependent on `send()` and I would like to add some headers.

**Comment by CodingAleCR** [comment]
> Trying out the Betamax implementation? What are you running into?

The thing with it is that it's dependant on `dart:io`, so I can't fully use your approach since we would loose web and desktop support, I have a similar approach but still in development.

**Comment by Mathew-Smith** [comment]
Would be great to see support for client.send(). Is it still in the pipeline?

**Comment by irvine5k** [comment]
any news?
