### ISSUE TITLE
Bad state: Can't finalize a finalized Request.

### ISSUE THREAD

**Issue by jlubeck** [CodingAleCR/http_interceptor#50]
I just got a chance to try this out, and the first time that I got my request to try, I got this exception:

`Bad state: Can't finalize a finalized Request.`

This is how I'm creating my initial client:
```dart
    var httpClient = HttpClientWithInterceptor.build(
        retryPolicy: ApiRetryPolicy(), interceptors: []);
```

And this is my RetryPolicy

```dart
class ApiRetryPolicy extends RetryPolicy {
  @override
  int maxRetryAttempts = 1;

  @override
  Future<bool> shouldAttemptRetryOnResponse(ResponseData response) async {
    if (response.statusCode == 302) {
      // Auth expired. Re-login and try again
      if (CurrentUser().email != null && CurrentUser().password != null) {
        var loginResults = await AuthenticationService.login(
            email: CurrentUser().email, password: CurrentUser().password);
        if (loginResults.isAuthorized) {
          CurrentUser().oAuth = loginResults.oAuth;
          // Re-try request
          return true;
        }
      }
    }
    return false;
  }
}
```

**Comment by CodingAleCR** [comment]
Will look into this ASAP.

Thanks for the issue!

**Comment by CodingAleCR** [comment]
Definitely a bug in need of a fix. Hopefully a patch version will come out this week for this issue. Thanks!

**Comment by CodingAleCR** [comment]
Might be related to resending the same request. Note to self on this SO post that might help come up with a solution.

**Comment by jlubeck** [comment]
Nice! Doesn't seem like 0.4.1 has this fix yet though, unless I'm missing something?

**Comment by CodingAleCR** [comment]
Hi, thanks for writing. Not just yet since I'm working on adding testing and a stable 1.0.0 release. It will involve breaking changes so I'm trying to be as thorough as I can be. In the meantime if you want I can try to isolate the change and release another patch version if that's ok.

**Comment by jlubeck** [comment]
That's fine, I can wait since this wasn't really a breaking issue. Thanks!

**Comment by sergey-koba-mobidev** [comment]
Hi, a patch version would be great indeed!

**Comment by CodingAleCR** [comment]
I will try to have by the weekend ✌🏼🙌🏼

**Comment by AhmedBenCheikh** [comment]
![Screen Shot 2021-07-27 at 10 51 07 AM](https://user-images.githubusercontent.com/18368441/127117004-981b28ba-656c-4e4d-95f3-8694b1c74162.png)

please any update for this issue !???

**Comment by CodingAleCR** [comment]
Hi, thanks for writing. This should have been fixed with 1.0.0

Can you give me a bit more of an explanation as to what you are trying to do? I want to figure out the cause of your situation since it's affecting the fix made earlier and fix the root cause. 😊

**Comment by AhmedBenCheikh** [comment]
Hi, thx for your reponse, i am trying to refresh my token, when i have 401 error i call my endpoint to refresh the token and i make retryPolicy in http to request the endpoknt again, if you have example for retryPolicy share me please because i don t find in documentation 
Thank you

**Comment by CodingAleCR** [comment]
Can you tell me or setup a repository where I can reproduce this? 

I have tried to make it fail but couldn't, maybe I am doing something differently.

**Comment by AhmedBenCheikh** [comment]
So, please share me your code, maybe my logic is wrong
thank you
