### ISSUE TITLE
Adding bodyBytes to RequestData

### ISSUE THREAD

**Issue by jcblancomartinez** [CodingAleCR/http_interceptor#52]
**Is your feature request related to a problem? Please describe.**

Currently, InterceptorContract's interceptRequest and interceptResponse methods receive RequestData.

RequestData has body field but not bodyBytes. 

We want access to bodyBytes to be able to decode it using the right encoding. In our case, we use UTF8, instead of latin1.

**Describe the solution you'd like**

I suggest bodyBytes gets added to RequestData.

**Describe alternatives you've considered**

I could encode in latin1 and decode it using UTF8.

**Additional context**

**Comment by CodingAleCR** [comment]
Hi, thanks, will look into adding this to the backlog and prioritizing as it is requested by users of the plugin.

**Comment by CodingAleCR** [comment]
This will be coming out soon, keep an eye out :)

**Comment by jcblancomartinez** [comment]
@CodingAleCR This is not yet available in http_interceptor 0.4.1. Can you please let me know when you release a version with these changes?

Thanks.

**Comment by CodingAleCR** [comment]
Will do. Stable 1.0.0 is coming out soon with this already in it ☺️🙌🏼
