### ISSUE TITLE
It's time to make it compatible with flutter web

### ISSUE THREAD

**Issue by ParthPahuja101** [CodingAleCR/http_interceptor#64]
Since flutter web is the next big thing, how come HTTP interceptor does not support flutter web?

**Comment by CodingAleCR** [comment]
It partially does. 

The package is compatible with Flutter Web, however, pub.dev and dart do not completely recognize this due to a particular feature (**badCertificateCallback**), I am currently trying to find a way to make it be recognized completely.

**Comment by CodingAleCR** [comment]
`badCertificatesCallback` was refactored out of the package but can still be achieved by following the docs of the 1.0.0 release coming soon.
