### ISSUE TITLE
Any chance for unbinding it from Flutter and making it a pure Dart package? 

### ISSUE THREAD

**Issue by caseyryan** [CodingAleCR/http_interceptor#67]
This interceptor is a really cool thing and I'm using it in several projects. Today I needed to use it on my Jaguar backend and I found out it depends on Flutter (for some reason). Of course I didn't want to add Flutter to my backend so taking a quick look into sources I found out there is absolutely nothing related to flutter inside the package and thus I could quickly make it work with a pure dart server. 
Could you please, also remove Flutter dependency from it so it could be used in any software written in dart?

**Comment by CodingAleCR** [comment]
Hi, yes, it definitely makes sense to do this. I will investigate on that front and ping back this issue when I have the info. Cheers!

**Comment by CodingAleCR** [comment]
@all-contributors please add @caseyryan  for ideas

**Comment by CodingAleCR** [comment]
I've removed the dependency on Flutter and will be part of 1.0.0 release ;)
