### ISSUE TITLE
Is this working with multipartrequests?

### ISSUE THREAD

**Issue by gutisalex** [CodingAleCR/http_interceptor#68]
I need to work with a soap API and all their endpoints run over a multipartrequest. Is there a way to intercept those as well? I could not figure that out yet? Do you have a little example?

KR

**Comment by CodingAleCR** [comment]
Multipart support is still being worked on, so as of right now, the latest release does not support it yet.

**Comment by gutisalex** [comment]
thx for the info...

**Comment by CodingAleCR** [comment]
Hey, unfortunately not yet since I have been too invested into my job and have not been able to give this as much time as it has needed. 😞

On the other hand, contributions are always welcomed and encouraged 🥳👌🏼

**Comment by CodingAleCR** [comment]
Multipart requests are added on #98 and to the 2.0.0 beta, feel free to try it out if you want ;)
