### ISSUE TITLE
BaseRequest field is missing in ResponseData

### ISSUE THREAD

**Issue by II11II** [CodingAleCR/http_interceptor#83]
In mapper method ```Response toHttpResponse()``` and factory ```factory ResponseData.fromHttpResponse(Response response)``` , mapping BaseRequest is missing.
P.s. in  ```Response toHttpResponse()``` method maps to Request only method and ```Uri```. But headers and bodies are missing

**Comment by CodingAleCR** [comment]
Thank you for opening the issue, I will get to it ASAP🔥

**Comment by II11II** [comment]
@CodingAleCR  Thank you)
I would like to ask why custom models f.e. ```RequestData and ResponseData```  are created?
May they replaced by default ```http``` library models, ```Request and Respone```   respectively?

**Comment by CodingAleCR** [comment]
They are needed in order to provide mutable versions of `Request` and `Response` classes on `http`. For example, query parameters are not mutable in `Request`, and thus you are not able to intercept those.

**Comment by CodingAleCR** [comment]
@all-contributors add @II11II for tests and code
