### ISSUE TITLE
Missing parameters for DELETE method

### ISSUE THREAD

**Issue by MaciejZuk** [CodingAleCR/http_interceptor#89]
Hello,

I have found one problem with DELETE method.

Intercepted_client.dart - line 144

> @override
  Future<Response> delete(
    Uri url, {
    Map<String, String>? headers,
    Object? body,
    Encoding? encoding,
  }) =>
      _sendUnstreamed(
        method: Method.DELETE,
        url: url,
        headers: headers,
      );

You have missed pass two parameters (body and encoding) for method _sendUnstreamed inside delete method.

Could you please correct it?

**Comment by CodingAleCR** [comment]
Once #90 is merged and a release is done, this should be fixed for you. @all-contributors add @MaciejZuk for bugs
