### ISSUE TITLE
Can it be used with MultipartRequest?

### ISSUE THREAD

**Issue by riskiadi** [CodingAleCR/http_interceptor#95]
How did you use multipart request using interceptor, i cant using interceptor with MultipartRequest() ?

final http = InterceptedHttp.build(interceptors: [Interceptor(),]);
var request = http.**MultipartRequest**("POST", uri);

`The method 'MultipartRequest' isn't defined for the type 'InterceptedHttp'. (Documentation)`

**Comment by CodingAleCR** [comment]
Hey, we have a beta version that supports `MultipartRequest`s, let me know if you are willing to try it out, it has a new API so you might need to adjust a few things (check out [the guide for more info](https://github.com/CodingAleCR/http_interceptor/blob/main/guides/migration_guide_2.0.0.md))

**Comment by riskiadi** [comment]
> Hi, this is not yet supported in the library. However, there's an open PR so hopefully it's coming soon.
> 
> #98

Yep, I'm so excited, thanks for developing "HTTP interceptor", I will try it later.

**Comment by dexcell** [comment]
Hi, i'm trying the http interceptor for multi part seems still not working.
somehow request fields always empty when intercepting.
also retry policy is ignored.

````
@override
  Future<http.BaseRequest> interceptRequest({required http.BaseRequest request}) async {
    if (request is http.MultipartRequest) {
      print(request.fields); // This will show empty, even though it is populated beforehand.
    }

    return request.copyWith(
      headers: headers,
    );
  }
````

**Comment by dexcell** [comment]
I sent pr to fix the problem, tested in my project. working well now.

**Comment by CodingAleCR** [comment]
> I sent pr to fix the problem, tested in my project. working well now.

Thank you! I will Review it during the weekend and if all looks good then create a new prerelease

**Comment by jsanz1209** [comment]
Hi @CodingAleCR, I need this functionality in my project, please, when will you accept this pull request?

Thanks in advance.

**Comment by CodingAleCR** [comment]
> Hi @CodingAleCR, I need this functionality in my project, please, when will you accept this pull request?
> 
> Thanks in advance.

Hey, @jsanz1209, the PR should be accepted and a new version before the weekend. Sorry for the delay! Happy Holidays!

**Comment by jsanz1209** [comment]
Hi @CodingAleCR,

Thanks for your support.

Is this hasn't been uploaded to pub.dev yet, right?

Greetings!

**Comment by CodingAleCR** [comment]
Hey, I completely missed the `beta.3` version release, I'm really sorry. But it's fixed now in a new `2.0.0-beta.4` version. Feel free to try it out, any feedback is always appreciated.

**Comment by fnicastri** [comment]
Using the beta.4 and trying to implement retry policy + jwt access token on a MultiPart request.
Now facing `Can't finalize a finalized MultipartRequest` 'cause after the first try the files are already finalized.
Any suggestion on how to fix this?

Thanks!

**Comment by CodingAleCR** [comment]
> Using the beta.4 and trying to implement retry policy + jwt access token on a MultiPart request. Now facing `Can't finalize a finalized MultipartRequest` 'cause after the first try the files are already finalized. Any suggestion on how to fix this?
> 
> Thanks!

That seems like an issue on the library itself, at least it has been on the past. I'll take a look and get back to you as soon as I can

**Comment by fnicastri** [comment]
> > Using the beta.4 and trying to implement retry policy + jwt access token on a MultiPart request. Now facing `Can't finalize a finalized MultipartRequest` 'cause after the first try the files are already finalized. Any suggestion on how to fix this?
> > Thanks!
> 
> That seems like an issue on the library itself, at least it has been on the past. I'll take a look and get back to you as soon as I can

Thanks!

**Comment by CodingAleCR** [comment]
Hi just an update, the library does have issues on this front. It seems we need to copy all `MultipartFile`s. Otherwise the upload retry won't work because each `MultipartFile` is a stream and has already been closed when the `MultipartRequest` is closed (for example when the request fails)

**Comment by fnicastri** [comment]
> 

yep, of course we should find a way to make it work on retried calls too.
For now I'm not using it with multipart, but I'm managing them externally.

thanks

**Comment by justincbeck** [comment]
I wish I could still set the retry policy independent of the constructor.

**Comment by CodingAleCR** [comment]
> I wish I could still set the retry policy independent of the constructor.

Like having a global retry policy?
