### ISSUE TITLE
Cancel http request

### ISSUE THREAD

**Issue by LucPham** [CodingAleCR/http_interceptor#97]
Hi,
Can I cancel a http processing request?

**Comment by CodingAleCR** [comment]
Hey, so sorry for the delayed response, as of right now there is not an exact way to cancel a request. I have noted the feature and added it to the roadmap. Cheers!

**Comment by vixez** [comment]
@CodingAleCR I have added a way to cancel active requests (not a single request) to this PR https://github.com/CodingAleCR/http_interceptor/pull/96
